version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Check style of Python Scripts with black
          command: |
            black --check otbenchmark --config pyproject.toml
      - run:
          name: Check style of Python Scripts with flake8
          command: |
            flake8 otbenchmark
      - run:
          name: Check style of Notebooks with black-nb
          command: |
            black-nb --check .
      - run:
          name: Test
          command: ./.circleci/run_docker_linux.sh
      - run:
          name: Install package in a venv with setup
          command: |
            python setup.py install
            mkdir tmp
            cp demo.py tmp
            cd tmp
            python demo.py
            cd ..
            rm -r tmp
      - run:
          name: Create package source distribution
          command: |
            python setup.py sdist

workflows:
  main:
    jobs:
      - build-and-test

